# Generated by Django 3.0.3 on 2020-05-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20200524_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='opened',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='sent',
            field=models.IntegerField(default=0),
        ),
    ]
