# Generated by Django 3.0.3 on 2020-05-25 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_auto_20200525_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='delay_H',
        ),
        migrations.AddField(
            model_name='email',
            name='delay',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='next_email_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
