# Generated by Django 3.0.3 on 2020-05-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_auto_20200525_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='send_email_date',
            field=models.DateField(null=True),
        ),
    ]
