# Generated by Django 3.0.3 on 2020-05-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_auto_20200525_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='index',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
