# Generated by Django 3.0.3 on 2020-05-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_auto_20200525_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('1', 'on'), ('0', 'of')], default=0, max_length=2),
        ),
    ]
