# Generated by Django 3.0.3 on 2020-05-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_auto_20200526_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='next_email_index',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
