# Generated by Django 3.0.7 on 2020-06-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_auto_20200607_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
