# Generated by Django 3.0.7 on 2020-06-12 21:19

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('mailing', '0012_campaign_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='sum_opened',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='sum_sent',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='unsubscribed',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
