# Generated by Django 3.0.7 on 2020-06-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_auto_20200613_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='unsubscribe',
            field=models.BooleanField(default=0, verbose_name='ביטול הרשמה'),
        ),
    ]
